In [146]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot

### Load Data

In [322]:
# Original 
csv_file = "現增資料 2000-2024.csv"
df = pd.read_csv(csv_file)
df

,證券代碼,除權日,上市別,總股本(仟元),面額,總股數(仟股),現金增資(仟股),股本膨脹,每千股認股數,現金認購價（元）,...,Y日內漲跌幅,Y+3收盤價,Y+5開收盤價,Y+10收盤價,Y開～Y+3收盤價,Y開～Y+5收盤價,Y開～Y+10收盤價,現金認購率 %,員工認購率 %,公開承銷率 %
0,2474 可成,2000/01/04,TSE,560542,10.0,56054,8000,14.3%,124.0000,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.40000,15.0,10
1,2380 虹光,2000/01/11,TSE,843350,10.0,84335,7500,8.9%,73.2090,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.32090,15.0,10
2,5345 天揚,2000/01/20,OTC,879545,10.0,87955,15000,17.1%,164.0000,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.40000,10.0,10
3,1528 恩德,2000/01/24,TSE,619000,10.0,61900,7000,11.3%,102.0000,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.20000,10.0,10
4,2323 中環,2000/01/31,TSE,10550787,10.0,1055079,80000,7.6%,61.0000,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.10000,10.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1751,6859 伯特光,2024/12/13,OTC,414700,10.0,41470,2000,4.8%,38.0035,138.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.80035,15.0,10
1752,3073 天方能源,2024/12/17,OTC,370996,10.0,37100,5000,13.5%,124.6120,53.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.46120,10.0,10
1753,6588 東典光電,2024/12/17,OTC,347008,10.0,34701,8000,23.1%,224.7120,32.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.47120,10.0,15
1754,1805 寶徠,2024/12/26,TSE,1349705,10.0,134970,30000,22.2%,228.6360,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.86360,10.0,10
1755,6153 嘉聯益,2024/12/30,TSE,6381777,10.0,638178,42000,6.6%,56.5487,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.65487,10.0,10

In [253]:
df.columns

Index(['證券代碼', '除權日', '上市別', '總股本(仟元)', '面額', '總股數(仟股)', '現金增資(仟股)', '股本膨脹',
       '每千股認股數', '現金認購價（元）', '增資公告日(X)', 'X 收盤價', 'X+1 開盤價', 'X+1 收盤價',
       'X~X+1跳空', 'X+1日內漲跌幅', 'X+1~X+3開對收', 'X+1~X+5開對收', 'X+1~T-5開對收',
       '現增補充日(T-5)', 'T-5收盤價', 'T-4開盤價', 'T-5收盤價套利空間％', 'T-5收~T-4開',
       'T-5收~T-4收', 'T-1收盤價', 'T-4開~T-1收漲跌幅', '現增除權日(T)', 'T開盤價', 'T收盤價',
       'T-1~T收對開盤價', 'T日內漲跌幅', 'T-1收盤價時之套利空間', '停止過戶-起(T+2)', 'Y-1收盤價',
       'T開~Y-1收', '繳款憑證發放日(Y)', 'Y開盤價', 'Y收盤價', 'Y-1收~Y開漲跌幅', 'Y日內漲跌幅',
       'Y+3收盤價', 'Y+5開收盤價', 'Y+10收盤價', 'Y開～Y+3收盤價', 'Y開～Y+5收盤價', 'Y開～Y+10收盤價',
       '現金認購率 %', '員工認購率 %', '公開承銷率 %'],
      dtype='object')

In [254]:
# CSV Merge 1999 to 2025 , Price Data
csv_file = "已調整股價 19991201-20031231.csv"
df_1 = pd.read_csv("已調整股價 19991201-20031231.csv", sep="\t", encoding="utf-16")
df_1

            證券代碼         年月日   開盤價(元)   收盤價(元)
0        1101 台泥   1999/12/1   4.0512   4.0305
1        1102 亞泥   1999/12/1   3.7731   3.7239
2        1103 嘉泥   1999/12/1   5.3214   5.1664
3        1104 環泥   1999/12/1   2.3492   2.2801
4        1108 幸福   1999/12/1   4.8672   4.6376
...          ...         ...      ...      ...
696276   9944 新麗  2003/12/31  12.0492  12.1362
696277  9945 潤泰新  2003/12/31   1.1366   1.1366
696278   9949 琉園  2003/12/31   7.1163   7.1163
696279   9951 皇田  2003/12/31  13.1677  13.1677
696280   9955 佳龍  2003/12/31  13.8282  14.1345

[696281 rows x 4 columns]

In [255]:
csv_file = "已調整股價 20040101-20141231.csv"
df_2 = pd.read_csv("已調整股價 20040101-20141231.csv", sep="\t", encoding="utf-16")
df_2

             證券代碼         年月日   開盤價(元)   收盤價(元)
0         1101 台泥  2004/01/02   4.0881   4.1861
1         1102 亞泥  2004/01/02   3.7189   3.9018
2         1103 嘉泥  2004/01/02  10.3844  10.7978
3         1104 環泥  2004/01/02   3.6179   3.7626
4         1108 幸福  2004/01/02   4.3881   4.5360
...           ...         ...      ...      ...
3139937   9951 皇田  2014/12/31  72.9597  72.9597
3139938   9955 佳龍  2014/12/31  18.5500  18.3500
3139939  9958 世紀鋼  2014/12/31   8.7141   8.8351
3139940  9960 邁達康  2014/12/31  15.0588  15.4791
3139941   9962 有益  2014/12/31   7.4136   7.4136

[3139942 rows x 4 columns]

In [257]:
csv_file = "已調整股價 20150101-20250227.csv"
df_3 = pd.read_csv("已調整股價 20150101-20250227.csv", sep="\t", encoding="utf-16")
df_3

             證券代碼         年月日    開盤價(元)    收盤價(元)
0         1101 台泥  2015/01/05   20.3688   20.1810
1         1102 亞泥  2015/01/05   22.6430   22.2647
2         1103 嘉泥  2015/01/05    9.7031    9.7717
3         1104 環泥  2015/01/05   14.1795   14.2069
4         1108 幸福  2015/01/05    6.6067    6.6708
...           ...         ...       ...       ...
4059663   9951 皇田  2025/02/27   58.9000   59.0000
4059664   9955 佳龍  2025/02/27   30.6500   30.2000
4059665  9958 世紀鋼  2025/02/27  185.5000  187.0000
4059666  9960 邁達康  2025/02/27   26.3500   26.3000
4059667   9962 有益  2025/02/27   16.1000   16.1500

[4059668 rows x 4 columns]

In [323]:
# Merge the dataframes into one by concatenating them
merged_df = pd.concat([df_1, df_2, df_3], ignore_index=True)
merged_df

             證券代碼         年月日    開盤價(元)    收盤價(元)
0         1101 台泥   1999/12/1    4.0512    4.0305
1         1102 亞泥   1999/12/1    3.7731    3.7239
2         1103 嘉泥   1999/12/1    5.3214    5.1664
3         1104 環泥   1999/12/1    2.3492    2.2801
4         1108 幸福   1999/12/1    4.8672    4.6376
...           ...         ...       ...       ...
7895886   9951 皇田  2025/02/27   58.9000   59.0000
7895887   9955 佳龍  2025/02/27   30.6500   30.2000
7895888  9958 世紀鋼  2025/02/27  185.5000  187.0000
7895889  9960 邁達康  2025/02/27   26.3500   26.3000
7895890   9962 有益  2025/02/27   16.1000   16.1500

[7895891 rows x 4 columns]

### 檢查空缺值

In [324]:

# 假設您已經用 pd.concat() 建立好了 merged_df
null_counts = merged_df.isna().sum()
print(null_counts)

# 如果想查看「整個 DataFrame 總共有多少個空值」:
total_null = merged_df.isna().sum().sum()
print("Total number of missing values in merged_df:", total_null)

證券代碼      0
年月日       0
開盤價(元)    0
收盤價(元)    0
dtype: int64
Total number of missing values in merged_df: 0

In [325]:
merged_df.columns

Index(['證券代碼', '年月日', '開盤價(元)', '收盤價(元)'], dtype='object')

### 把merged_df的收盤價時間對應df應有的增資案收盤價時間

### X 收盤價

In [326]:
df['增資公告日(X)'] = pd.to_datetime(df['增資公告日(X)'], errors='coerce')
merged_df['年月日'] = pd.to_datetime(merged_df['年月日'], errors='coerce')

df_merged = df.merge(
    merged_df[['證券代碼','年月日','收盤價(元)']], 
    left_on=['證券代碼','增資公告日(X)'],
    right_on=['證券代碼','年月日'],
    how='left'  )

df_merged['X 收盤價'] = df_merged['X 收盤價'].fillna(df_merged['收盤價(元)'])


df_merged.drop(columns=['年月日', '收盤價(元)'], inplace=True)

df_merged

,證券代碼,除權日,上市別,總股本(仟元),面額,總股數(仟股),現金增資(仟股),股本膨脹,每千股認股數,現金認購價（元）,...,Y日內漲跌幅,Y+3收盤價,Y+5開收盤價,Y+10收盤價,Y開～Y+3收盤價,Y開～Y+5收盤價,Y開～Y+10收盤價,現金認購率 %,員工認購率 %,公開承銷率 %
0,2474 可成,2000/01/04,TSE,560542,10.0,56054,8000,14.3%,124.0000,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.40000,15.0,10
1,2380 虹光,2000/01/11,TSE,843350,10.0,84335,7500,8.9%,73.2090,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.32090,15.0,10
2,5345 天揚,2000/01/20,OTC,879545,10.0,87955,15000,17.1%,164.0000,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.40000,10.0,10
3,1528 恩德,2000/01/24,TSE,619000,10.0,61900,7000,11.3%,102.0000,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.20000,10.0,10
4,2323 中環,2000/01/31,TSE,10550787,10.0,1055079,80000,7.6%,61.0000,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.10000,10.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1751,6859 伯特光,2024/12/13,OTC,414700,10.0,41470,2000,4.8%,38.0035,138.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.80035,15.0,10
1752,3073 天方能源,2024/12/17,OTC,370996,10.0,37100,5000,13.5%,124.6120,53.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.46120,10.0,10
1753,6588 東典光電,2024/12/17,OTC,347008,10.0,34701,8000,23.1%,224.7120,32.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.47120,10.0,15
1754,1805 寶徠,2024/12/26,TSE,1349705,10.0,134970,30000,22.2%,228.6360,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.86360,10.0,10
1755,6153 嘉聯益,2024/12/30,TSE,6381777,10.0,638178,42000,6.6%,56.5487,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.65487,10.0,10

In [327]:
df_merged.columns

Index(['證券代碼', '除權日', '上市別', '總股本(仟元)', '面額', '總股數(仟股)', '現金增資(仟股)', '股本膨脹',
       '每千股認股數', '現金認購價（元）', '增資公告日(X)', 'X 收盤價', 'X+1 開盤價', 'X+1 收盤價',
       'X~X+1跳空', 'X+1日內漲跌幅', 'X+1~X+3開對收', 'X+1~X+5開對收', 'X+1~T-5開對收',
       '現增補充日(T-5)', 'T-5收盤價', 'T-4開盤價', 'T-5收盤價套利空間％', 'T-5收~T-4開',
       'T-5收~T-4收', 'T-1收盤價', 'T-4開~T-1收漲跌幅', '現增除權日(T)', 'T開盤價', 'T收盤價',
       'T-1~T收對開盤價', 'T日內漲跌幅', 'T-1收盤價時之套利空間', '停止過戶-起(T+2)', 'Y-1收盤價',
       'T開~Y-1收', '繳款憑證發放日(Y)', 'Y開盤價', 'Y收盤價', 'Y-1收~Y開漲跌幅', 'Y日內漲跌幅',
       'Y+3收盤價', 'Y+5開收盤價', 'Y+10收盤價', 'Y開～Y+3收盤價', 'Y開～Y+5收盤價', 'Y開～Y+10收盤價',
       '現金認購率 %', '員工認購率 %', '公開承銷率 %'],
      dtype='object')

In [328]:
df_merged['X 收盤價']

0        10.2641
1        41.8442
2            NaN
3            NaN
4        89.0201
          ...
1751    183.7038
1752     57.8864
1753     36.7337
1754     19.7716
1755     19.9027
Name: X 收盤價, Length: 1756, dtype: float64

In [298]:
df_merged.columns

Index(['證券代碼', '除權日', '上市別', '總股本(仟元)', '面額', '總股數(仟股)', '現金增資(仟股)', '股本膨脹',
       '每千股認股數', '現金認購價（元）', '增資公告日(X)', 'X 收盤價', 'X+1 開盤價', 'X+1 收盤價',
       'X~X+1跳空', 'X+1日內漲跌幅', 'X+1~X+3開對收', 'X+1~X+5開對收', 'X+1~T-5開對收',
       '現增補充日(T-5)', 'T-5收盤價', 'T-4開盤價', 'T-5收盤價套利空間％', 'T-5收~T-4開',
       'T-5收~T-4收', 'T-1收盤價', 'T-4開~T-1收漲跌幅', '現增除權日(T)', 'T開盤價', 'T收盤價',
       'T-1~T收對開盤價', 'T日內漲跌幅', 'T-1收盤價時之套利空間', '停止過戶-起(T+2)', 'Y-1收盤價',
       'T開~Y-1收', '繳款憑證發放日(Y)', 'Y開盤價', 'Y收盤價', 'Y-1收~Y開漲跌幅', 'Y日內漲跌幅',
       'Y+3收盤價', 'Y+5開收盤價', 'Y+10收盤價', 'Y開～Y+3收盤價', 'Y開～Y+5收盤價', 'Y開～Y+10收盤價',
       '現金認購率 %', '員工認購率 %', '公開承銷率 %'],
      dtype='object')

In [329]:
df_merged

,證券代碼,除權日,上市別,總股本(仟元),面額,總股數(仟股),現金增資(仟股),股本膨脹,每千股認股數,現金認購價（元）,...,Y日內漲跌幅,Y+3收盤價,Y+5開收盤價,Y+10收盤價,Y開～Y+3收盤價,Y開～Y+5收盤價,Y開～Y+10收盤價,現金認購率 %,員工認購率 %,公開承銷率 %
0,2474 可成,2000/01/04,TSE,560542,10.0,56054,8000,14.3%,124.0000,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.40000,15.0,10
1,2380 虹光,2000/01/11,TSE,843350,10.0,84335,7500,8.9%,73.2090,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.32090,15.0,10
2,5345 天揚,2000/01/20,OTC,879545,10.0,87955,15000,17.1%,164.0000,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.40000,10.0,10
3,1528 恩德,2000/01/24,TSE,619000,10.0,61900,7000,11.3%,102.0000,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.20000,10.0,10
4,2323 中環,2000/01/31,TSE,10550787,10.0,1055079,80000,7.6%,61.0000,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.10000,10.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1751,6859 伯特光,2024/12/13,OTC,414700,10.0,41470,2000,4.8%,38.0035,138.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.80035,15.0,10
1752,3073 天方能源,2024/12/17,OTC,370996,10.0,37100,5000,13.5%,124.6120,53.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.46120,10.0,10
1753,6588 東典光電,2024/12/17,OTC,347008,10.0,34701,8000,23.1%,224.7120,32.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.47120,10.0,15
1754,1805 寶徠,2024/12/26,TSE,1349705,10.0,134970,30000,22.2%,228.6360,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.86360,10.0,10
1755,6153 嘉聯益,2024/12/30,TSE,6381777,10.0,638178,42000,6.6%,56.5487,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.65487,10.0,10

In [330]:
df_merged['X 收盤價']

0        10.2641
1        41.8442
2            NaN
3            NaN
4        89.0201
          ...
1751    183.7038
1752     57.8864
1753     36.7337
1754     19.7716
1755     19.9027
Name: X 收盤價, Length: 1756, dtype: float64

In [331]:
df['增資公告日(X+1)'] = df['增資公告日(X)'] + pd.Timedelta(days=1)

In [302]:
df_merged.columns

Index(['證券代碼', '除權日', '上市別', '總股本(仟元)', '面額', '總股數(仟股)', '現金增資(仟股)', '股本膨脹',
       '每千股認股數', '現金認購價（元）', '增資公告日(X)', 'X 收盤價', 'X+1 開盤價', 'X+1 收盤價',
       'X~X+1跳空', 'X+1日內漲跌幅', 'X+1~X+3開對收', 'X+1~X+5開對收', 'X+1~T-5開對收',
       '現增補充日(T-5)', 'T-5收盤價', 'T-4開盤價', 'T-5收盤價套利空間％', 'T-5收~T-4開',
       'T-5收~T-4收', 'T-1收盤價', 'T-4開~T-1收漲跌幅', '現增除權日(T)', 'T開盤價', 'T收盤價',
       'T-1~T收對開盤價', 'T日內漲跌幅', 'T-1收盤價時之套利空間', '停止過戶-起(T+2)', 'Y-1收盤價',
       'T開~Y-1收', '繳款憑證發放日(Y)', 'Y開盤價', 'Y收盤價', 'Y-1收~Y開漲跌幅', 'Y日內漲跌幅',
       'Y+3收盤價', 'Y+5開收盤價', 'Y+10收盤價', 'Y開～Y+3收盤價', 'Y開～Y+5收盤價', 'Y開～Y+10收盤價',
       '現金認購率 %', '員工認購率 %', '公開承銷率 %'],
      dtype='object')

In [332]:
df['增資公告日(X+1)']

0      1999-12-15
1      1999-12-25
2      2000-01-01
3      1999-12-30
4      2000-01-20
          ...
1751   2024-11-26
1752   2024-12-03
1753   2024-10-23
1754   2024-10-09
1755   2024-10-30
Name: 增資公告日(X+1), Length: 1756, dtype: datetime64[ns]

In [333]:
import pandas as pd

# 1. 先確保有 X+1 欄位
df['增資公告日(X+1)'] = df['增資公告日(X)'] + pd.Timedelta(days=1)

# 2. 合併取得 X 收盤價
df_merged = df.merge(
    merged_df[['證券代碼','年月日','收盤價(元)']], 
    left_on=['證券代碼','增資公告日(X)'],
    right_on=['證券代碼','年月日'],
    how='left'
)
df_merged['X 收盤價'] = df_merged['X 收盤價'].fillna(df_merged['收盤價(元)'])
df_merged.drop(columns=['年月日', '收盤價(元)'], inplace=True)

# 3. 合併取得 X+1「開盤價」與「收盤價」
df_merged = df_merged.merge(
    # 一次帶入「開盤價(元)」、「收盤價(元)」，並改成「X+1 開盤價」、「X+1 收盤價」
    merged_df[['證券代碼','年月日','開盤價(元)','收盤價(元)']].rename(
        columns={
            '開盤價(元)': 'X+1 開盤價',
            '收盤價(元)': 'X+1 收盤價'
        }
    ),
    left_on=['證券代碼','增資公告日(X+1)'],
    right_on=['證券代碼','年月日'],
    how='left'
)
df_merged.drop(columns=['年月日'], inplace=True)

# 4. 檢視結果
df_merged.head()

,證券代碼,除權日,上市別,總股本(仟元),面額,總股數(仟股),現金增資(仟股),股本膨脹,每千股認股數,現金認購價（元）,...,Y+10收盤價,Y開～Y+3收盤價,Y開～Y+5收盤價,Y開～Y+10收盤價,現金認購率 %,員工認購率 %,公開承銷率 %,增資公告日(X+1),X+1 開盤價_y,X+1 收盤價_y
0,2474 可成,2000/01/04,TSE,560542,10.0,56054,8000,14.3%,124.000,165.0,...,NaN,NaN,NaN,NaN,12.4000,15.0,10,1999-12-15,10.2641,10.4825
1,2380 虹光,2000/01/11,TSE,843350,10.0,84335,7500,8.9%,73.209,110.0,...,NaN,NaN,NaN,NaN,7.3209,15.0,10,1999-12-25,NaN,NaN
2,5345 天揚,2000/01/20,OTC,879545,10.0,87955,15000,17.1%,164.000,60.0,...,NaN,NaN,NaN,NaN,16.4000,10.0,10,2000-01-01,NaN,NaN
3,1528 恩德,2000/01/24,TSE,619000,10.0,61900,7000,11.3%,102.000,20.0,...,NaN,NaN,NaN,NaN,10.2000,10.0,10,1999-12-30,NaN,NaN
4,2323 中環,2000/01/31,TSE,10550787,10.0,1055079,80000,7.6%,61.000,120.0,...,NaN,NaN,NaN,NaN,6.1000,10.0,10,2000-01-20,90.0552,91.6079

In [334]:
# 1. 用 _y 欄位的值填補 _x 欄位中的 NaN
df_merged['X+1 開盤價_x'] = df_merged['X+1 開盤價_x'].fillna(df_merged['X+1 開盤價_y'])
df_merged['X+1 收盤價_x'] = df_merged['X+1 收盤價_x'].fillna(df_merged['X+1 收盤價_y'])

# 2. 最後可根據需求選擇留下哪個欄位
#    例如把 _x 欄位 rename 成想要的正式欄位名稱
df_merged.rename(
    columns={
        'X+1 開盤價_x': 'X+1 開盤價',
        'X+1 收盤價_x': 'X+1 收盤價'
    },
    inplace=True
)

# 3. 也可以將 _y 欄位直接刪除，避免重複
df_merged.drop(columns=['X+1 開盤價_y','X+1 收盤價_y'], inplace=True, errors='ignore')

# 檢查最終結果
df_merged.head()

,證券代碼,除權日,上市別,總股本(仟元),面額,總股數(仟股),現金增資(仟股),股本膨脹,每千股認股數,現金認購價（元）,...,Y+3收盤價,Y+5開收盤價,Y+10收盤價,Y開～Y+3收盤價,Y開～Y+5收盤價,Y開～Y+10收盤價,現金認購率 %,員工認購率 %,公開承銷率 %,增資公告日(X+1)
0,2474 可成,2000/01/04,TSE,560542,10.0,56054,8000,14.3%,124.000,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,12.4000,15.0,10,1999-12-15
1,2380 虹光,2000/01/11,TSE,843350,10.0,84335,7500,8.9%,73.209,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,7.3209,15.0,10,1999-12-25
2,5345 天揚,2000/01/20,OTC,879545,10.0,87955,15000,17.1%,164.000,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,16.4000,10.0,10,2000-01-01
3,1528 恩德,2000/01/24,TSE,619000,10.0,61900,7000,11.3%,102.000,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,10.2000,10.0,10,1999-12-30
4,2323 中環,2000/01/31,TSE,10550787,10.0,1055079,80000,7.6%,61.000,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,6.1000,10.0,10,2000-01-20

In [272]:
df_merged.tail(50)

,證券代碼,除權日,上市別,總股本(仟元),面額,總股數(仟股),現金增資(仟股),股本膨脹,每千股認股數,現金認購價（元）,...,Y+3收盤價,Y+5開收盤價,Y+10收盤價,Y開～Y+3收盤價,Y開～Y+5收盤價,Y開～Y+10收盤價,現金認購率 %,員工認購率 %,公開承銷率 %,增資公告日(X+1)
1706,5871 中租-KY,2024/09/05,TSE,16778639,10.0,1677864,31000,1.8%,12.9392,125.00,...,NaN,NaN,NaN,NaN,NaN,NaN,1.29392,15.0,10,2024-08-10
1707,6629 泰金-KY,2024/09/12,OTC,383162,10.0,38316,2600,6.8%,61.8767,109.00,...,NaN,NaN,NaN,NaN,NaN,NaN,6.18767,5.0,10,2024-08-28
1708,5213 亞昕,2024/09/13,OTC,5806497,10.0,580650,50000,8.6%,75.5815,37.45,...,NaN,NaN,NaN,NaN,NaN,NaN,7.55815,10.0,10,2024-08-17
1709,2228 劍麟,2024/09/16,TSE,795303,10.0,79530,3750,4.7%,37.1139,88.00,...,NaN,NaN,NaN,NaN,NaN,NaN,3.71139,15.0,10,2024-08-28
1710,2464 盟立,2024/09/16,TSE,2045312,10.0,204531,9000,4.4%,36.8228,63.00,...,NaN,NaN,NaN,NaN,NaN,NaN,3.68228,10.0,10,2024-08-30
1711,6535 順藥,2024/09/20,OTC,1689318,10.0,168932,4000,2.4%,19.4061,225.00,...,NaN,NaN,NaN,NaN,NaN,NaN,1.94061,10.0,10,2024-09-05
1712,3558 神準,2024/09/24,OTC,590609,10.0,59061,10000,16.9%,163.0630,125.00,...,NaN,NaN,NaN,NaN,NaN,NaN,16.30630,10.0,10,2024-09-07
1713,6182 合晶,2024/09/24,OTC,5727437,10.0,572744,30000,5.2%,44.2230,26.50,...,NaN,NaN,NaN,NaN,NaN,NaN,4.42230,10.0,10,2024-08-28
1714,1589 永冠-KY,2024/10/01,TSE,1331359,10.0,133136,15000,11.3%,114.2750,40.00,...,NaN,NaN,NaN,NaN,NaN,NaN,11.42750,0.0,10,2024-09-04
1715,5347 世界,2024/10/01,OTC,18389823,10.0,1838982,200000,10.9%,91.5202,88.00,...,NaN,NaN,NaN,NaN,NaN,NaN,9.15202,15.0,10,2024-09-14
1716,2722 夏都,2024/10/04,TSE,1431697,10.0,143170,22000,15.4%,136.1730,30.00,...,NaN,NaN,NaN,NaN,NaN,NaN,13.61730,15.0,10,2024-09-17
1717,6248 沛波,2024/10/04,OTC,999561,10.0,99956,30000,30.0%,321.6300,27.00,...,NaN,NaN,NaN,NaN,NaN,NaN,32.16300,15.0,10,2024-09-20
1718,5864 致和證,2024/10/07,OTC,4208292,10.0,420829,81500,19.4%,180.1350,13.80,...,NaN,NaN,NaN,NaN,NaN,NaN,18.01350,15.0,10,2024-09-21
1719,9939 宏全,2024/10/07,TSE,2957859,10.0,295786,8000,2.7%,22.2388,133.00,...,NaN,NaN,NaN,NaN,NaN,NaN,2.22388,10.0,10,2024-09-21
1720,3516 亞帝歐,2024/10/08,OTC,595609,10.0,59561,6000,10.1%,84.0166,21.00,...,NaN,NaN,NaN,NaN,NaN,NaN,8.40166,15.0,10,2024-09-21
1721,4927 泰鼎-KY,2024/10/11,TSE,2199380,10.0,219938,30000,13.6%,142.1520,40.00,...,NaN,NaN,NaN,NaN,NaN,NaN,14.21520,0.0,10,2024-09-26
1722,2034 允強,2024/10/14,TSE,5202256,10.0,520226,50000,9.6%,79.7489,19.00,...,NaN,NaN,NaN,NaN,NaN,NaN,7.97489,15.0,10,2024-09-12
1723,4174 浩鼎,2024/10/15,OTC,2632394,10.0,263239,33800,12.8%,117.8520,64.00,...,NaN,NaN,NaN,NaN,NaN,NaN,11.78520,10.0,10,2024-09-25
1724,9935 慶豐富,2024/10/15,TSE,1778389,10.0,177839,4000,2.2%,17.3071,27.30,...,NaN,NaN,NaN,NaN,NaN,NaN,1.73071,15.0,10,2024-09-27
1725,6235 華孚,2024/10/18,TSE,1998045,10.0,199805,5800,2.9%,23.9170,50.00,...,NaN,NaN,NaN,NaN,NaN,NaN,2.39170,10.0,10,2024-09-21
1726,1815 富喬,2024/10/23,OTC,5157778,10.0,515778,50000,9.7%,85.8779,18.50,...,NaN,NaN,NaN,NaN,NaN,NaN,8.58779,10.0,10,2024-09-25
1727,1584 精剛,2024/10/24,OTC,2324705,10.0,232471,40000,17.2%,155.8680,32.00,...,NaN,NaN,NaN,NaN,NaN,NaN,15.58680,15.0,10,2024-09-27
1728,2367 燿華,2024/10/24,TSE,7094072,10.0,709407,40000,5.6%,47.8035,26.00,...,NaN,NaN,NaN,NaN,NaN,NaN,4.78035,10.0,10,2024-10-05
1729,6425 易發,2024/10/24,OTC,486020,10.0,48602,5000,10.3%,86.0052,68.00,...,NaN,NaN,NaN,NaN,NaN,NaN,8.60052,15.0,10,2024-10-08
1730,6706 惠特,2024/10/28,TSE,785769,10.0,78577,5000,6.4%,50.9671,132.00,...,NaN,NaN,NaN,NaN,NaN,NaN,5.09671,15.0,10,2024-10-12
1731,9928 中視,2024/10/28,TSE,707246,10.0,70725,10000,14.1%,131.7420,15.00,...,NaN,NaN,NaN,NaN,NaN,NaN,13.17420,10.0,10,2024-10-12
1732,2061 風青,2024/10/29,OTC,573781,10.0,57378,10000,17.4%,158.3010,18.60,...,NaN,NaN,NaN,NaN,NaN,NaN,15.83010,15.0,10,2024-10-01
1733,6596 寬宏藝術,2024/10/30,OTC,380000,10.0,38000,5000,13.2%,113.6360,70.00,...,NaN,NaN,NaN,NaN,NaN,NaN,11.36360,15.0,10,2024-10-16
1734,6690 安碁資訊,2024/11/01,OTC,301152,10.0,30115,8000,26.6%,289.3930,200.00,...,NaN,NaN,NaN,NaN,NaN,NaN,28.93930,10.0,10,2024-10-16
1735,1587 吉茂,2024/11/06,TSE,800557,10.0,80056,8000,10.0%,88.8202,30.00,...,NaN,NaN,NaN,NaN,NaN,NaN,8.88202,10.0,10,2024-10-23
1736,6576 逸達,2024/11/07,OTC,1548178,10.0,154818,18000,11.6%,105.2730,76.00,...,NaN,NaN,NaN,NaN,NaN,NaN,10.52730,10.0,10,2024-10-16
1737,9802 鈺齊-KY,2024/11/11,TSE,2009899,10.0,200990,10000,5.0%,39.4053,76.00,...,NaN,NaN,NaN,NaN,NaN,NaN,3.94053,15.0,10,2024-08-20
1738,6550 北極星藥業-KY,2024/11/13,TSE,7702063,10.0,770206,24000,3.1%,25.7302,49.00,...,NaN,NaN,NaN,NaN,NaN,NaN,2.57302,10.0,10,2024-10-30
1739,5284 jpp-KY,2024/11/14,TSE,509289,10.0,50929,3000,5.9%,50.0742,113.00,...,NaN,NaN,NaN,NaN,NaN,NaN,5.00742,10.0,10,2024-10-22
1740,5548 安倉,2024/11/15,OTC,564605,10.0,56461,15000,26.6%,289.4320,26.00,...,NaN,NaN,NaN,NaN,NaN,NaN,28.94320,10.0,10,2024-10-29
1741,5381 合正,2024/11/19,OTC,2437268,10.0,243727,30000,12.3%,112.2930,24.00,...,NaN,NaN,NaN,NaN,NaN,NaN,11.22930,10.0,10,2024-10-23
1742,2734 易飛網,2024/11/27,OTC,572598,10.0,57260,15000,26.2%,266.2110,23.50,...,NaN,NaN,NaN,NaN,NaN,NaN,26.62110,15.0,10,2024-11-13
1743,2867 三商壽,2024/11/28,TSE,56995010,10.0,5699501,300000,5.3%,44.4486,6.30,...,NaN,NaN,NaN,NaN,NaN,NaN,4.44486,10.0,10,2024-11-14
1744,3059 華晶科,2024/12/04,TSE,3058000,10.0,305800,27000,8.8%,78.0601,26.80,...,NaN,NaN,NaN,NaN,NaN,NaN,7.80601,10.0,10,2024-11-20
1745,3346 麗清,2024/12/05,TSE,1211590,10.0,121159,6000,5.0%,41.6814,32.00,...,NaN,NaN,NaN,NaN,NaN,NaN,4.16814,10.0,10,2024-08-10
1746,1438 三地開發,2024/12/06,TSE,1112057,10.0,111206,20000,18.0%,175.4280,50.00,...,NaN,NaN,NaN,NaN,NaN,NaN,17.54280,10.0,10,2024-11-21
1747,4503 金雨,2024/12/09,OTC,783133,10.0,78313,12000,15.3%,135.7190,37.50,...,NaN,NaN,NaN,NaN,NaN,NaN,13.57190,15.0,10,2024-11-22
1748,3259 鑫創,2024/12/12,OTC,729659,10.0,72966,16000,21.9%,224.6960,22.00,...,NaN,NaN,NaN,NaN,NaN,NaN,22.46960,10.0,10,2024-11-27
1749,6657 華安,2024/12/12,TSE,884940,10.0,88494,12000,13.6%,125.5000,48.00,...,NaN,NaN,NaN,NaN,NaN,NaN,12.55000,10.0,10,2024-11-21
1750,8444 綠河-KY,2024/12/12,OTC,1104668,10.0,110467,10000,9.1%,80.0241,31.00,...,NaN,NaN,NaN,NaN,NaN,NaN,8.00241,10.0,10,2024-11-27
1751,6859 伯特光,2024/12/13,OTC,414700,10.0,41470,2000,4.8%,38.0035,138.00,...,NaN,NaN,NaN,NaN,NaN,NaN,3.80035,15.0,10,2024-11-26
1752,3073 天方能源,2024/12/17,OTC,370996,10.0,37100,5000,13.5%,124.6120,53.00,...,NaN,NaN,NaN,NaN,NaN,NaN,12.46120,10.0,10,2024-12-03
1753,6588 東典光電,2024/12/17,OTC,347008,10.0,34701,8000,23.1%,224.7120,32.50,...,NaN,NaN,NaN,NaN,NaN,NaN,22.47120,10.0,15,2024-10-23
1754,1805 寶徠,2024/12/26,TSE,1349705,10.0,134970,30000,22.2%,228.6360,14.00,...,NaN,NaN,NaN,NaN,NaN,NaN,22.86360,10.0,10,2024-10-09
1755,6153 嘉聯益,2024/12/30,TSE,6381777,10.0,638178,42000,6.6%,56.5487,14.00,...,NaN,NaN,NaN,NaN,NaN,NaN,5.65487,10.0,10,2024-10-30

In [335]:
df_merged['X+1 開盤價'].tail(50)

1706         NaN
1707    135.7713
1708         NaN
1709     98.8745
1710     86.1756
1711    251.2984
1712         NaN
1713     34.1656
1714     40.2991
1715         NaN
1716         NaN
1717     31.1015
1718         NaN
1719         NaN
1720         NaN
1721     54.5828
1722     21.9315
1723     75.2522
1724     33.3928
1725         NaN
1726     21.8734
1727     37.9187
1728         NaN
1729     81.3214
1730         NaN
1731         NaN
1732     24.5598
1733     72.0088
1734    208.4003
1735     41.0943
1736     79.7791
1737    111.9100
1738     49.9505
1739    139.4119
1740     31.5059
1741     27.0672
1742     29.3505
1743      6.9590
1744     32.4978
1745         NaN
1746     51.4162
1747     48.6447
1748     25.9499
1749     50.5420
1750     28.9873
1751    183.7038
1752     58.2815
1753     37.8225
1754     20.6746
1755     19.4571
Name: X+1 開盤價, dtype: float64

In [336]:
df_merged['X+1 開盤價'].tail

<bound method NDFrame.tail of 0        10.2641
1            NaN
2            NaN
3            NaN
4        90.0552
          ...
1751    183.7038
1752     58.2815
1753     37.8225
1754     20.6746
1755     19.4571
Name: X+1 開盤價, Length: 1756, dtype: float64>

In [337]:
df_merged['X+1 開盤價']

0        10.2641
1            NaN
2            NaN
3            NaN
4        90.0552
          ...
1751    183.7038
1752     58.2815
1753     37.8225
1754     20.6746
1755     19.4571
Name: X+1 開盤價, Length: 1756, dtype: float64

In [338]:
df_merged['X+1 收盤價']

0        10.4825
1            NaN
2            NaN
3            NaN
4        91.6079
          ...
1751    191.1112
1752     60.7511
1753     38.0592
1754     19.2488
1755     19.3581
Name: X+1 收盤價, Length: 1756, dtype: float64

In [339]:
df_merged['X 收盤價']

0        10.2641
1        41.8442
2            NaN
3            NaN
4        89.0201
          ...
1751    183.7038
1752     57.8864
1753     36.7337
1754     19.7716
1755     19.9027
Name: X 收盤價, Length: 1756, dtype: float64

In [340]:
num_nan_x1_open = df_merged['X+1 開盤價'].isna().sum()
print("NaN count in X+1 開盤價:", num_nan_x1_open)

NaN count in X+1 開盤價: 613

### 處理空缺項，往後找一非NaN的值填入

In [341]:
df.columns

Index(['證券代碼', '除權日', '上市別', '總股本(仟元)', '面額', '總股數(仟股)', '現金增資(仟股)', '股本膨脹',
       '每千股認股數', '現金認購價（元）', '增資公告日(X)', 'X 收盤價', 'X+1 開盤價', 'X+1 收盤價',
       'X~X+1跳空', 'X+1日內漲跌幅', 'X+1~X+3開對收', 'X+1~X+5開對收', 'X+1~T-5開對收',
       '現增補充日(T-5)', 'T-5收盤價', 'T-4開盤價', 'T-5收盤價套利空間％', 'T-5收~T-4開',
       'T-5收~T-4收', 'T-1收盤價', 'T-4開~T-1收漲跌幅', '現增除權日(T)', 'T開盤價', 'T收盤價',
       'T-1~T收對開盤價', 'T日內漲跌幅', 'T-1收盤價時之套利空間', '停止過戶-起(T+2)', 'Y-1收盤價',
       'T開~Y-1收', '繳款憑證發放日(Y)', 'Y開盤價', 'Y收盤價', 'Y-1收~Y開漲跌幅', 'Y日內漲跌幅',
       'Y+3收盤價', 'Y+5開收盤價', 'Y+10收盤價', 'Y開～Y+3收盤價', 'Y開～Y+5收盤價', 'Y開～Y+10收盤價',
       '現金認購率 %', '員工認購率 %', '公開承銷率 %', '增資公告日(X+1)'],
      dtype='object')

In [342]:
df_merged.sort_values(by=['證券代碼','增資公告日(X)'], inplace=True)

columns_to_fill = ['X 收盤價', 'X+1 開盤價', 'X+1 收盤價']
df_merged[columns_to_fill] = df_merged.groupby('證券代碼')[columns_to_fill].bfill()

In [343]:
df_merged['X 收盤價']

497     12.9479
333     11.3190
534     12.5826
1052    14.2694
1016    99.1760
         ...
346      6.3349
373      7.4500
699      8.4026
1100    62.4282
286     14.0242
Name: X 收盤價, Length: 1756, dtype: float64

In [344]:
df_merged['X+1 開盤價']

497     12.9479
333     11.3190
534     12.6277
1052        NaN
1016    98.4599
         ...
346      6.3349
373      8.4729
699      8.4729
1100    62.4282
286     14.1055
Name: X+1 開盤價, Length: 1756, dtype: float64

In [345]:
df_merged['X+1 收盤價']

497     12.7964
333     11.1054
534     12.4022
1052        NaN
1016    98.8179
         ...
346      6.3046
373      8.4026
699      8.4026
1100    61.0867
286     13.9591
Name: X+1 收盤價, Length: 1756, dtype: float64

### 把剩下NaN填上

In [346]:
df_merged.sort_values(by=['證券代碼','增資公告日(X)'], inplace=True)

columns_to_fill = ['X 收盤價', 'X+1 開盤價', 'X+1 收盤價']

# 先後填
df_merged[columns_to_fill] = (
    df_merged
    .groupby('證券代碼')[columns_to_fill]
    .apply(lambda g: g.bfill().ffill())
)

# 若還有 NaN，就用 0(或其他值) 補
df_merged[columns_to_fill] = df_merged[columns_to_fill].fillna(0)

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 12304, in _reindex_for_setitem
    reindexed_value = value.reindex(index)._values
                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/series.py", line 4977, in reindex
    return super().reindex(
           ^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 5521, in reindex
    return self._reindex_axes(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 5544, in _reindex_axes
    new_index, indexer = ax.reindex(
                         ^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 4437, in reindex
    target = self._wrap_reindex_result(target, indexer, preserve_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/multi.py", line 2602, in _wrap_reindex_result
    target = MultiIndex.from_tuples(target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/multi.py", line 220, in new_meth
    return meth(self_or_cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/multi.py", line 615, in from_tuples
    arrays = list(lib.tuples_to_object_array(tuples).T)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2977, in pandas._libs.lib.tuples_to_object_array
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/b6/fb60dc_d6bx6dt630rrghmbc0000gn/T/ipykernel_91393/3251562816.py", line 6, in <module>
    df_merged[columns_to_fill] = (
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 4079, in __setitem__
    self._setitem_array(key, value)
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 4123, in _setitem_array
    self[k1] = value[k2]
    ~~~~^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 4091, in __setitem__
    self._set_item(key, value)
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 4300, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 5036, in _sanitize_column
    return _reindex_for_setitem(value, self.index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 12311, in _reindex_for_setitem
    raise TypeError(
TypeError: incompatible index of inserted column with frame index

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2102, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1310, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1199, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1071, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 953, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1037, in get_records
    FIs.append(FrameInfo("Raw frame", filename, lineno, frame, code))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 700, in __init__
    ix = inspect.getsourcelines(frame)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/inspect.py", line 1244, in getsourcelines
    lines, lnum = findsource(object)
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/lawrencechang/anaconda3/lib/python3.11/inspect.py", line 1073, in findsource
    raise OSError('source code not available')
OSError: source code not available

In [347]:
df_merged.sort_values(by=['證券代碼','增資公告日(X)'], inplace=True)
columns_to_fill = ['X 收盤價', 'X+1 開盤價', 'X+1 收盤價']

df_merged[columns_to_fill] = (
    df_merged
    .groupby('證券代碼')[columns_to_fill]
    .transform(lambda g: g.bfill().ffill())
)

df_merged[columns_to_fill] = df_merged[columns_to_fill].fillna(0)

In [348]:
num_nan_x1_open = df_merged['X+1 開盤價'].isna().sum()
print("NaN count in X+1 開盤價:", num_nan_x1_open)

NaN count in X+1 開盤價: 0

In [349]:
df_merged['X+1 收盤價']

497     12.7964
333     11.1054
534     12.4022
1052     0.0000
1016    98.8179
         ...
346      6.3046
373      8.4026
699      8.4026
1100    61.0867
286     13.9591
Name: X+1 收盤價, Length: 1756, dtype: float64

### 檔案匯出

In [196]:
# 指定匯出路徑與檔名
output_path = "增資案完整df_merged_output.csv"

# 若資料中有中文欄位或內容，記得指定編碼 (如 'utf-8-sig')
df_merged.to_csv(output_path, index=False, encoding='utf-8-sig')

### 驗證數量

In [350]:
check_df = df_merged[df_merged['增資公告日(X+1)'].notna()].copy()
print("左表的非空日期數量：", len(check_df))

左表的非空日期數量： 1756